use customer_behavior;

select top 10 * from customer;

select * from customer 
where customer_id is null
or
age is null
or
gender is null
or
item_purchased is null
or
category is null
or
purchase_amount is null
or
location is null
or
size is null
or
color is null
or
season is null
or
review_rating is null
or
subscription_status is null
or
shipping_type is null
or
discount_applied is null
or
previous_purchases is null
or
payment_method is null
or
frequency_of_purchases is null
or
age_group is null
or
purchase_frequency_days is null;



--Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as revenue 
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select Avg (purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?

select top 5 item_purchased, Round(avg(review_rating),2) as " Average review rating"
from customer
group by item_purchased
order by AVG(review_rating) desc;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping?

select shipping_type,Round(AVG(purchase_amount),2)
from customer
where shipping_type in ('standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between

select subscription_status,
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as Avg_spend,
ROUND(AVG(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,Avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5
    item_purchased,
    ROUND(
      CAST(SUM(CASE WHEN UPPER(discount_applied) = 'YES' THEN 1 ELSE 0 END) AS DECIMAL(10,4))
      * 100.0
      / CAST(COUNT(*) AS DECIMAL(10,4))
    , 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

 with customer_type as(
 select customer_id,previous_purchases,
 case
     when previous_purchases = 1 then 'New'
	 when previous_purchases Between 2 And 10 then 'Returning'
	 Else 'Loyal'
	 End As customer_segment
	 from customer
 )

 select customer_segment, count(*) as 'Number of customers'
 from customer_type
 group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?

with item_counts as(
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?

select age_group,
COUNT(purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue



